#!/bin/sh -e
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD -s 10.0.0.0/8 -j ACCEPT
iptables -I INPUT -p tcp --dport 2021 -j ACCEPT
iptables -I INPUT -p udp --dport 2021 -j ACCEPT
iptables -I INPUT -p tcp --dport 2069 -j ACCEPT
iptables -I INPUT -p udp --dport 2069 -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.0.0.0/8 ! -d 10.0.0.0/8 -j SNAT --to 66.42.50.98
exit 0
